name: Build and push Apptainer images

on:
  push:
    paths:
      - 'apptainer/*.def'
      - '.github/workflows/build-and-push-apptainer.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Optional image tag (e.g. 25.06). Defaults to latest + commit SHA.'
        required: false
        type: string

jobs:
  build-push:
    strategy:
      matrix:
        image: [jureca, leonardo, lumi]
    name: Build & Publish SIF Artifact (${{ matrix.image }})
    runs-on: 
      - runs-on=${{github.run_id}}/family=i7ie
    permissions:
      contents: read

    steps:
      # - name: Delete huge unnecessary tools folder
      #   run: rm -rf /opt/hostedtoolcache

      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Show disk usage before cleanup
      #   run: |
      #     echo "=== df -h (before) ===" && df -h
      #     echo "=== Top-level disk usage under /opt ===" && du -h -d1 /opt | sort -hr | head -n20

      # - name: Free up disk space on runner (optional but helpful)
      #   run: |
      #     sudo rm -rf /usr/share/dotnet || true
      #     sudo rm -rf /usr/local/lib/android || true
      #     sudo rm -rf /opt/ghc || true
      #     sudo rm -rf /opt/hostedtoolcache || true
      #     sudo docker system prune -af || true

      #     sudo rm -rf /usr/local/julia* /usr/share/swift /usr/lib/jvm /usr/local/lib/node_modules || true

      #     # Purge additional unneeded APT packages (Java, and common build toolchains)
      #     sudo apt-get remove -y '^openjdk-.*' '^jdk-.*' '^dotnet-.*' || true
      #     sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel || true
      #     sudo apt-get autoremove -y || true
      #     sudo apt-get clean || true

      #     # Remove caches
      #     sudo rm -rf /opt/microsoft /opt/az /opt/google /opt/pipx /opt/actionarchivecache /opt/runner-cache || true

      # - name: Show disk usage after cleanup
      #   run: |
      #     echo "=== df -h (before) ===" && df -h
      #     echo "=== Top-level disk usage under /opt ===" && du -h -d1 /opt | sort -hr | head -n20
      
      - name: Install Apptainer
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get update
          sudo apt-get install -y apptainer

      - name: Build SIF from definition file
        run: |
          apptainer --verbose build --fakeroot eval_env-${{ matrix.image }}.sif apptainer/${{ matrix.image }}.def

      - name: Install Hugging Face Hub CLI
        run: pip install --upgrade "huggingface_hub[cli]"

      - name: Login to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: huggingface-cli login --token "$HF_TOKEN"  

      - name: Upload SIF to Hugging Face Hub
        env:
          HF_REPO: timurcarstensen/testing
        run: |
          huggingface-cli upload \
            "$HF_REPO" \
            eval_env-${{ matrix.image }}.sif \
            eval_env-${{ matrix.image }}.sif \
            --repo-type dataset \
            --commit-message "[chore] update ${{ matrix.image }} image"