name: Build and push Apptainer image (Leonardo)

on:
  push:
    paths:
      - 'apptainer/leonardo.def'
      - '.github/workflows/build-and-push-apptainer.yml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Optional image tag (e.g. 25.06). Defaults to latest + commit SHA.'
        required: false
        type: string

jobs:
  build-push:
    name: Build & Publish SIF Artifact (Apptainer only)
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show disk usage before cleanup
        run: |
          echo "=== df -h (before) ===" && df -h
          echo "=== Top-level disk usage under /opt ===" && du -h -d1 /opt | sort -hr | head -n20

      - name: Free up disk space on runner (optional but helpful)
        run: |
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /usr/local/lib/android || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf /opt/hostedtoolcache || true
          sudo docker system prune -af || true

          sudo rm -rf /usr/local/julia* /usr/share/swift /usr/lib/jvm /usr/local/lib/node_modules || true

          # Purge additional unneeded APT packages (Java, and common build toolchains)
          sudo apt-get remove -y '^openjdk-.*' '^jdk-.*' '^dotnet-.*' || true
          sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel || true
          sudo apt-get autoremove -y || true
          sudo apt-get clean || true

          # Remove caches
          sudo rm -rf /opt/microsoft /opt/az /opt/google /opt/pipx /opt/actionarchivecache /opt/runner-cache || true

      - name: Show disk usage after cleanup
        run: |
          echo "=== df -h (before) ===" && df -h
          echo "=== Top-level disk usage under /opt ===" && du -h -d1 /opt | sort -hr | head -n20
      
      - name: Install Apptainer
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:apptainer/ppa
          sudo apt-get update
          sudo apt-get install -y apptainer

      - name: Build SIF from definition file
        run: |
          apptainer --verbose build --fakeroot eval_env-leonardo.sif apptainer/leonardo.def

      - name: Upload SIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: eval_env-leonardo.sif
          path: eval_env-leonardo.sif 