name: Build and push Docker image

on:
  # Rebuild automatically when the Dockerfile (or this workflow) changes
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/build-and-push-docker.yml'
  # Allow manual trigger from the GitHub UI with optional custom tag
  workflow_dispatch:
    inputs:
      tag:
        description: 'Optional image tag (e.g. 25.06). Defaults to latest + commit SHA.'
        required: false
        type: string

jobs:
  build-push:
    name: Build & Push to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write   # needed to push to ghcr.io
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Buildx/QEMU for multi-arch (works even if you only need linux/amd64)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags & labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/eval_env
          # Tags produced by default:
          #  • latest (main branch) or branch name
          #  • sha-<short SHA>
          #  • any tag provided via workflow_dispatch input
          tags: |
            type=raw,latest
            type=sha
            type=raw,${{ github.event.inputs.tag }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 