name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install dependencies
      run: |
        uv venv
        uv pip install ruff

    - name: Check code formatting with Ruff
      run: |
        uv run ruff format --check --diff .

    - name: Lint with Ruff
      run: |
        uv run ruff check .

    - name: Type check with mypy
      run: |
        uv pip install mypy
        uv run mypy . --ignore-missing-imports || true
      continue-on-error: true

  yaml-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python 3.12
      run: uv python install 3.12

    - name: Install yamllint
      run: |
        uv venv
        uv pip install yamllint

    - name: Lint YAML files
      run: |
        uv run yamllint . || true
      continue-on-error: true

